apiVersion: skaffold/v4beta6
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./shirinBlog-dev-sub/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: shahab5191/shirinblog-recipe
      context: ./
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
